version: "3.3"
services:
  api:
    container_name: "api"
    image: nzeong/easystock:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    restart: 'always'
    environment:
      - PORT=8080
      - SERVER_PORT=8080
    expose:
      - "8080"
    volumes:
      - .:/app